# Generated by Django 5.2.7 on 2025-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Civil Engineer', 'Civil Engineer'), ('Chemical Engineer', 'Chemical Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Industrial Engineer', 'Industrial Engineer'), ('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electrical Engineer', 'Electrical Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Electronic Engineer', 'Electronic Engineer')], default='Computer Science', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Civil Engineer', 'Civil Engineer'), ('Chemical Engineer', 'Chemical Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Industrial Engineer', 'Industrial Engineer'), ('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electrical Engineer', 'Electrical Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Electronic Engineer', 'Electronic Engineer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
