# Generated by Django 5.2.7 on 2025-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20251027_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Architecture', 'Architecture'), ('Chemical Engineer', 'Chemical Engineer'), ('Civil Engineer', 'Civil Engineer'), ('Computer Engineer', 'Computer Engineer'), ('Computer Science', 'Computer Science'), ('Electrical Engineer', 'Electrical Engineer'), ('Electronic Engineer', 'Electronic Engineer'), ('Industrial Engineer', 'Industrial Engineer'), ('Information Technology', 'Information Technology'), ('Mechanical Engineer', 'Mechanical Engineer')], max_length=50),
        ),
    ]
