# Generated by Django 5.2.7 on 2025-11-05 11:54

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=rooms.models.campus_image_upload_path),
        ),
    ]
