# Generated by Django 5.2.7 on 2025-11-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_campus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='image',
        ),
        migrations.AddField(
            model_name='campus',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the campus image from the web', null=True),
        ),
    ]
