# Generated by Django 5.2.7 on 2025-11-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_campus_image_campus_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the room image from the web', null=True),
        ),
    ]
