# Generated by Django 5.2.7 on 2025-10-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to='reservation_letters/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='letter_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
