# Generated by Django 5.2.7 on 2025-10-27 09:09

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_letter_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to=reservations.models.reservation_letter_upload_path),
        ),
    ]
