# Generated by Django 5.2.7 on 2025-11-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_letter_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approval_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
